title: Blog posts
description: 
author: Yi-Hsuan Tseng
github: https://github.com/yrsheld
about: Thoughts in Progress
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/yi-hsuan-tseng-463656273/"
    - icon: fa-github
      link: "https://github.com/yrsheld"

urls:
    - text: My Projects
      url: /projects/

url: "hsuan.tseng13@gmail.com"
baseurl: "hsuan.tseng13@gmail.com"
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
